### ISSUE TITLE
npm install on Mac not working

### ISSUE THREAD

**Issue by idoor88** [worldsibu/convector-example-fabcar-rest#1]
After I cloned the project to my local Mac, and in the project root directory I run npm install, it generated a bunch of errors such as:

rm: ./Release/.deps/Release/obj.target/grpc/deps/grpc/src/core/lib/channel/channel_args.o.d.raw: No such file or directory
make: *** [Release/obj.target/grpc/deps/grpc/src/core/lib/channel/channel_args.o] Error 1
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/channel/channel_stack.o
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/usr/local/Cellar/node/11.4.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--library=static_library" "--module=/Users/projects/convector-example-fabcar-rest/node_modules/fabric-client/node_modules/grpc/src/node/extension_binary/node-v67-darwin-x64-unknown/grpc_node.node" "--module_name=grpc_node" "--module_path=/Users/projects/convector-example-fabcar-rest/node_modules/fabric-client/node_modules/grpc/src/node/extension_binary/node-v67-darwin-x64-unknown" "--napi_version=3" "--node_abi_napi=napi"
gyp ERR! cwd /Users/projects/convector-example-fabcar-rest/node_modules/fabric-client/node_modules/grpc
gyp ERR! node -v v11.4.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 

Any clues?
Thanks

**Comment by idoor88** [comment]
resolved, install node-gyp
